# config_vertex.yaml
workerPoolSpecs:
    machineSpec:
        machineType: n1-standard-8
        acceleratorType: NVIDIA_TESLA_T4
        acceleratorCount: 1
    replicaCount: 1
    containerSpec:
        imageUri: europe-west1-docker.pkg.dev/dtumlops-484208/dtumlops-dockerimages/gpu-image
        command:
          - uv
          - run
          - main.py
          - +experiment=llm
        env:
        - name: WANDB_API_KEY
          value: $WANDB_API_KEY