_target_: src.lightning_modules.DummyModule

network:
  _target_: src.networks.DummyNetwork
  input_size: 10
  output_size: 1

loss_fn:
  _target_: src.losses.MSELoss

optimizer:
  _target_: torch.optim.AdamW
  _partial_: True
  lr: 1.e-4
  weight_decay: 0.0

lr_scheduler:
  # this is a boring scheduler that does nothing
  # here we specify the scheduler
  scheduler:
    _target_: torch.optim.lr_scheduler.ConstantLR
    _partial_: True
    factor: 1.0
    total_iters: 1
  # this is pytorch lightning logic
  # see: https://lightning.ai/docs/pytorch/stable/_modules/lightning/pytorch/core/module.html#LightningModule.configure_optimizers
  monitor: 'val_loss'
  interval: 'step'
  frequency: 1
