_target_: src.lightning_modules.CausalLLM

network:
  _target_: src.networks.CausalTransformer
  checkpoint: distilbert/distilgpt2

tokenizer: ${tokenizer}

optimizer:
  _target_: torch.optim.AdamW
  _partial_: True
  lr: 1.e-4
  weight_decay: 0.0

lr_scheduler:
  scheduler:
    _target_: torch.optim.lr_scheduler.ConstantLR
    _partial_: True
    factor: 1.0
    total_iters: 1
  monitor: 'val_loss'
  interval: 'step'
  frequency: 1
